baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'El meu lloc'
theme = "tale"

[menu]
  [[menu.main]]
    identifier = "contacto"
    name = "contacto"
    title = "contacto"
    url = "/contacto/"
    weight = 0
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    title = "Posts"
    url = "/posts/"
    weight = 0